### ISSUE TITLE
Statistics.js issue

### ISSUE THREAD

**Issue by jhorton44** [fdesjardins/coverage-viewer#10]
Hi! This tool looks awesome. Would love to use it.

Getting an error when I try to run it, wondering if it's due to array.prototype.flatten being deprecated, and is now 'array.prototype.flat' ?
```
npm WARN deprecated array.prototype.flatten@1.2.1: This method has been renamed to "flat" - please use `array.prototype.flat` instead
```

I run:
```coverage-viewer coverage.json -s /Users/myName/Documents/GitHub/MyProject/src -o ./coverage
/usr/local/lib/node_modules/coverage-viewer/lib/statistics.js:22
    line => line.stats.find(stat => stat.name === 'Hits').value !== 0

TypeError: Cannot read property 'value' of undefined
    at lines.filter.line (/usr/local/lib/node_modules/coverage-viewer/lib/statistics.js:22:58)
    at Array.filter (<anonymous>)
    at getLinesHit (/usr/local/lib/node_modules/coverage-viewer/lib/statistics.js:21:9)
    at exports.getLineStats.data (/usr/local/lib/node_modules/coverage-viewer/lib/statistics.js:39:20)
    at files.map.file (/usr/local/lib/node_modules/coverage-viewer/lib/statistics.js:100:18)
    at Array.map (<anonymous>)
    at exports.getFileStats.data (/usr/local/lib/node_modules/coverage-viewer/lib/statistics.js:97:16)
    at renderFile (/usr/local/lib/node_modules/coverage-viewer/lib/render.js:34:21)
    at files.map.file (/usr/local/lib/node_modules/coverage-viewer/lib/render.js:52:13)
    at Array.map (<anonymous>)
```

If not, I'm probably doing something wrong. Would you mind helping me?

Thanks so much

**Comment by fdesjardins** [comment]
Hey @jhorton44, thanks for the feedback. You have a point about flatten, but I'm not sure if that's the underlying issue. I know someone else identified some differences in the latest version of Coverlet output format, I suspect this is related.

I haven't had time to make a proper update, but I'll try to carve some time out to take another look soon.

**Comment by jhorton44** [comment]
@fdesjardins I see, that makes sense. Thank you for your response and for creating this tool. Look forward to an update sometime in the future, I hope :)
Best wishes
